### ISSUE TITLE
Not showing story and feature

### ISSUE THREAD

**Issue by tommyz0123** [allure-framework/allure-js-commons#16]
I ran the allure-js-commons/test/runtime.spec.js using protractor.  Generated the report using allure command line, it shows all tests under 'allure-runtime', the top level describe.  It's not sowing feature 'labels', and story 'add'.  What's missing/wrong?

**Comment by just-boris** [comment]
Hello! 
That is kinda of expected behavior because the file that you are running is unit test. All real output is disabled there.

If you are looking for an example of the test setup, I'd recommend you look at https://github.com/allure-examples/mocha-allure-example and all other repositories under this organization.
